import React, { useState, useEffect, useCallback } from 'react';
import ReflectionCard from './ReflectionCard';
import { reflectionLogger as logger } from '../../utils/logger';
import { fetchReflections, initReflectionSocket, disconnectReflectionSocket, subscribeToConnectionStatus } from '../../services/reflectionService';
import { formatRelativeTime } from '../../utils/dateFormatter';

/**
 * ReflectionView component for viewing autonomous AI reflections
 * This component displays reflections generated by the SELO DSP autonomous reflection system
 */
const ReflectionView = ({ userId }) => {
  const [reflections, setReflections] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [activeType, setActiveType] = useState('daily');
  const [error, setError] = useState(null);
  const [socketStatus, setSocketStatus] = useState('disconnected');

  // Reflection types available in the system
  const reflectionTypes = [
    { id: 'daily', name: 'Daily', description: 'Daily thoughts and patterns' },
    { id: 'weekly', name: 'Weekly', description: 'Weekly synthesis and growth' },
    { id: 'emotional', name: 'Emotional', description: 'Emotional state analysis' },
  ];

  // Function to load reflections from the API (memoized)
  const loadReflections = useCallback(async () => {
    if (!userId) return;
    setIsLoading(true);
    setError(null);
    try {
      const response = await fetchReflections(userId, activeType);
      // Filter out internal reflection types (relationship_seed, etc.)
      const validReflections = (response.reflections || []).filter(r => {
        const type = r.reflection_type || r.type;
        return type !== 'relationship_seed' && type !== 'relationship_questions';
      });
      setReflections(validReflections);
    } catch (err) {
      logger.error('Failed to load reflections', err);
      setError('Failed to load reflections. Please try again.');
    } finally {
      setIsLoading(false);
    }
  }, [userId, activeType]);

  // Handle real-time reflection updates
  const handleReflectionUpdate = useCallback((update) => {
    // Debug logging removed for production
    if (update.status === 'generating') {
      // Reflection generating
    } else if (update.status === 'complete') {
      loadReflections();
    }
  }, [loadReflections]);

  // Load reflections on component mount and when reflection type changes
  useEffect(() => {
    loadReflections();
  }, [loadReflections]);

  // Set up Socket.IO connection for real-time updates
  useEffect(() => {
    if (!userId) return;

    // Debug logging removed for production
    initReflectionSocket(userId, handleReflectionUpdate);

    // Subscribe to centralized connection status
    const unsubscribeStatus = subscribeToConnectionStatus((status) => {
      setSocketStatus(status);
      // Debug logging removed for production
    });

    // Cleanup on unmount
    return () => {
      // Debug logging removed for production
      disconnectReflectionSocket();
      if (unsubscribeStatus) unsubscribeStatus();
    };
  }, [userId, handleReflectionUpdate]);

  // loadReflections is defined above with useCallback



  return (
    <div className="flex flex-col space-y-6">
      <div className="flex justify-between items-center">
        <h2 className="text-2xl font-semibold text-[var(--color-accent)]">SELO's Reflections</h2>
        <div className="flex items-center gap-3">
          <button
            onClick={loadReflections}
            className="text-sm px-3 py-1 rounded-md bg-[var(--color-bg-elev-2)] hover:bg-[var(--color-bg-elev-1)] border border-[var(--color-border)] text-[var(--color-accent)]"
            title="Refresh reflections"
          >
            Refresh
          </button>
          <span className={`text-sm px-2 py-1 rounded-full ${
            socketStatus === 'connected' ? 'bg-green-500/20 text-green-300' : 'bg-red-500/20 text-red-300'
          }`}>
            {socketStatus === 'connected' ? 'Real-time Connected' : 'Offline Mode'}
          </span>
        </div>
      </div>
      
      {/* Reflection type selector */}
      <div className="flex space-x-2 overflow-x-auto pb-2">
        {reflectionTypes.map(type => (
          <button
            key={type.id}
            onClick={() => setActiveType(type.id)}
            className={`px-4 py-2 rounded-lg text-sm transition-colors border ${
              activeType === type.id 
                ? 'bg-[var(--color-bg-elev-2)] text-[var(--color-accent)] border-[var(--color-border)]' 
                : 'bg-[var(--color-bg-elev-1)] text-[var(--color-text-secondary)] hover:bg-[var(--color-bg-elev-2)] border-[var(--color-border)]'
            }`}
          >
            {type.name}
          </button>
        ))}
      </div>
      
      {/* Reflection schedule information */}
      <div className="border border-[var(--color-border)] bg-[var(--color-bg-elev-1)] rounded-lg overflow-hidden">
        <div className="p-5">
          <div className="flex items-start space-x-4">
            <div className="text-[var(--color-accent)]">
              <svg xmlns="http://www.w3.org/2000/svg" className="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
              </svg>
            </div>
            <div className="flex-1">
              <h3 className="text-xl font-medium text-[var(--color-accent)]">
                Autonomous Reflection Schedule
              </h3>
              <p className="text-sm text-gray-400 mt-1">
                {activeType === 'daily' && 'Daily reflections are autonomously generated every day at midnight.'}
                {activeType === 'weekly' && 'Weekly reflections are autonomously generated every Sunday at midnight.'}
                {activeType === 'emotional' && 'Emotional reflections are generated based on significant emotional events.'}
              </p>
            </div>
          </div>
        </div>
        <div className="px-5 py-3 bg-[var(--color-bg-elev-2)] border-t border-[var(--color-border)]">
          <p className="text-xs text-[var(--color-text-muted)]">
            Reflections are automatically generated based on persona memories, emotional state, and learned attributes.
            They help your AI evolve its understanding and identity without manual intervention.
          </p>
        </div>
      </div>
      
      {/* Error display */}
      {error && (
        <div className="p-4 rounded-lg bg-red-500/10 border border-red-500/40 text-red-300">
          {error}
        </div>
      )}
      
      {/* Reflections list */}
      <div className="space-y-4">
        <h3 className="text-xl font-medium text-[var(--color-accent)]">
          Past {reflectionTypes.find(t => t.id === activeType)?.name} Reflections
        </h3>
        
        {isLoading ? (
          <div className="p-8 flex justify-center">
            <div className="animate-pulse flex space-x-2 items-center">
              <div className="h-3 w-3 bg-[var(--color-accent)] rounded-full"></div>
              <div className="h-3 w-3 bg-[var(--color-accent)] rounded-full animation-delay-200"></div>
              <div className="h-3 w-3 bg-[var(--color-accent)] rounded-full animation-delay-400"></div>
            </div>
          </div>
        ) : reflections.length > 0 ? (
          <div className="space-y-4">
            {reflections.map(reflection => (
              <ReflectionCard
                key={reflection.id}
                reflection={reflection}
                timeAgo={formatRelativeTime(reflection.created_at)}
              />
            ))}
          </div>
        ) : (
          <div className="p-8 text-center text-[var(--color-text-muted)] border border-dashed border-[var(--color-border)] rounded-lg">
            <p>No {activeType} reflections available yet.</p>
            <p className="text-sm mt-2">Generate your first one to begin building your AI's self-awareness.</p>
          </div>
        )}
      </div>
    </div>
  );
};

export default ReflectionView;
