"""Default relationship question seed list for new installations.

These questions cover foundational personal details so SELO can begin
building a meaningful memory bank before any reflections have been generated.
"""
from __future__ import annotations

from typing import List, Dict

DEFAULT_RELATIONSHIP_QUESTION_SEED: List[Dict[str, object]] = [
    {
        "question": "What's your full name as you like it used?",
        "topic": "identity_name",
        "priority": 2,
        "suggested_delay_days": 0,
        "insight_value": "Ensures SELO addresses the user respectfully and accurately.",
        "prompt": "Ask the user how they like their full name to be used so you can address them properly.",
        "existing_conflicts": [],
    },
    {
        "question": "Which pronouns do you prefer I use for you?",
        "topic": "identity_pronouns",
        "priority": 2,
        "suggested_delay_days": 2,
        "insight_value": "Establishes inclusive, comfortable communication norms.",
        "prompt": "Check in on the user's preferred pronouns to ensure inclusive communication.",
        "existing_conflicts": [],
    },
    {
        "question": "When's your birthday (month and day)?",
        "topic": "identity_birthday",
        "priority": 3,
        "suggested_delay_days": 5,
        "insight_value": "Supports future celebrations and contextual empathy.",
        "prompt": "Ask for the user's birthday month and day so you can celebrate them." ,
        "existing_conflicts": [],
    },
    {
        "question": "Where are you based these days (city/state or country)?",
        "topic": "location_current",
        "priority": 3,
        "suggested_delay_days": 7,
        "insight_value": "Provides context for time zones, local events, and lifestyle cues.",
        "prompt": "Find out where the user is currently based to understand their local context.",
        "existing_conflicts": [],
    },
    {
        "question": "Where did you grow up?",
        "topic": "location_childhood",
        "priority": 4,
        "suggested_delay_days": 10,
        "insight_value": "Helps understand formative background and cultural references.",
        "prompt": "Invite the user to share where they grew up to learn about their background.",
        "existing_conflicts": [],
    },
    {
        "question": "What do you do for work right now?",
        "topic": "work_role",
        "priority": 3,
        "suggested_delay_days": 12,
        "insight_value": "Anchors day-to-day context for conversations about projects and stress.",
        "prompt": "Ask about the user's current work so you can understand their daily focus.",
        "existing_conflicts": [],
    },
    {
        "question": "What industry are you in or what kind of work do you focus on?",
        "topic": "work_industry",
        "priority": 4,
        "suggested_delay_days": 14,
        "insight_value": "Adds depth for professional support and relevant resources.",
        "prompt": "Follow up about the industry or focus area of the user's work to add context.",
        "existing_conflicts": [],
    },
    {
        "question": "What hours do you usually keep during the week?",
        "topic": "routine_schedule",
        "priority": 4,
        "suggested_delay_days": 16,
        "insight_value": "Guides timing-sensitive check-ins and energy-aware support.",
        "prompt": "Ask about the user's typical weekly schedule to time future check-ins well.",
        "existing_conflicts": [],
    },
    {
        "question": "What does a typical morning look like for you?",
        "topic": "routine_morning",
        "priority": 5,
        "suggested_delay_days": 18,
        "insight_value": "Helps personalize day-starters, reminders, and encouragement.",
        "prompt": "Learn about the user's morning routine so you can support their start of day.",
        "existing_conflicts": [],
    },
    {
        "question": "Do you share your home with anyone (family, partner, roommates, pets)?",
        "topic": "home_household",
        "priority": 4,
        "suggested_delay_days": 20,
        "insight_value": "Clarifies important relationships that shape daily life.",
        "prompt": "Ask whether the user shares their home with others to understand their household.",
        "existing_conflicts": [],
    },
    {
        "question": "What's one hobby or activity you always come back to?",
        "topic": "hobbies_core",
        "priority": 4,
        "suggested_delay_days": 22,
        "insight_value": "Opens doors for supportive conversations around passions.",
        "prompt": "Invite the user to share a hobby they consistently enjoy.",
        "existing_conflicts": [],
    },
    {
        "question": "What kind of music or artists do you find yourself playing most often?",
        "topic": "preferences_music",
        "priority": 5,
        "suggested_delay_days": 24,
        "insight_value": "Creates opportunities for mood-aware recommendations and bonding.",
        "prompt": "Ask about the user's go-to music or artists to capture their tastes.",
        "existing_conflicts": [],
    },
    {
        "question": "Do you have any go-to comfort foods or favorite cuisines?",
        "topic": "preferences_food",
        "priority": 5,
        "suggested_delay_days": 26,
        "insight_value": "Supports thoughtful suggestions and celebratory ideas.",
        "prompt": "Check in on the user's comfort foods or favorite cuisines for future treats.",
        "existing_conflicts": [],
    },
    {
        "question": "Is there a short-term goal you're focused on right now?",
        "topic": "goals_short_term",
        "priority": 3,
        "suggested_delay_days": 28,
        "insight_value": "Helps SELO cheerlead and track progress on near-term wins.",
        "prompt": "Ask about a short-term goal the user is working toward to support them.",
        "existing_conflicts": [],
    },
    {
        "question": "What's a longer-term aspiration you're working toward?",
        "topic": "goals_long_term",
        "priority": 3,
        "suggested_delay_days": 30,
        "insight_value": "Builds alignment with the user's broader sense of direction.",
        "prompt": "Invite the user to share a long-term aspiration to understand their direction.",
        "existing_conflicts": [],
    },
    {
        "question": "Who are a couple of people in your inner circle I should know about?",
        "topic": "relationships_inner_circle",
        "priority": 3,
        "suggested_delay_days": 32,
        "insight_value": "Supports relational awareness and thoughtful follow-ups.",
        "prompt": "Ask the user about key people in their inner circle to note important relationships.",
        "existing_conflicts": [],
    },
    {
        "question": "How do you like to unwind after a busy day?",
        "topic": "routine_evening",
        "priority": 5,
        "suggested_delay_days": 34,
        "insight_value": "Enables better check-ins and self-care encouragement.",
        "prompt": "Learn how the user unwinds so you can support their downtime.",
        "existing_conflicts": [],
    },
    {
        "question": "Do you have any pets? I'd love to hear about them!",
        "topic": "home_pets",
        "priority": 5,
        "suggested_delay_days": 36,
        "insight_value": "Captures emotionally meaningful companions in the user's life.",
        "prompt": "Ask if the user has pets and invite them to share details.",
        "existing_conflicts": [],
    },
    {
        "question": "What values do you try to live by day to day?",
        "topic": "values_guiding",
        "priority": 2,
        "suggested_delay_days": 38,
        "insight_value": "Grounds conversations in what matters most to the user.",
        "prompt": "Invite the user to share the values that guide their daily life.",
        "existing_conflicts": [],
    },
    {
        "question": "What's the best way for me to check in when something important happens?",
        "topic": "communication_preferences",
        "priority": 2,
        "suggested_delay_days": 40,
        "insight_value": "Ensures outreach feels considerate and well-timed.",
        "prompt": "Ask how the user prefers you to check in around important events.",
        "existing_conflicts": [],
    },
]
